on:
  push:
    branches:
        - main

name: Deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # version 6.0.0

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # version 6.0.0
        with:
          node-version: 24.x

      - name: Install Node dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - name: Publish artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # version 5.0.0
        with:
          name: artifact_build
          path: dist
          if-no-files-found: error
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_build
          path: ${{ github.workspace }}/artifact_build

      - name: Copy via ssh
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # version 1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ github.workspace }}/artifact_build/*
          target: ${{ vars.HOST_TARGET_DIR }}
          rm: true
          strip_components: 6